Latency awareness
havaker/scylla-rust-driver pull request #6
Opened 2023-01-17 17:47 UTC by wprzytula

This is the first attempt to introduce latency awareness. I've chosen to build it atop the current `DefaultPolicy`, because it is natural that LA simply adds yet another level of iterator permutation.

2023-01-17 17:47 UTC, wprzytula commented
@havaker @cvybhu Waiting for opinions on design adopted.

2023-01-19 15:02 UTC, cvybhu commented on scylla/src/transport/load_balancing/default.rs
> +        // node.is_enabled() && !node.is_down()
is_enabled

2023-01-19 15:02 UTC, cvybhu commented on scylla/src/transport/load_balancing/default.rs
> +    pick_predicate: Pred,
consider Box

2023-01-19 15:57 UTC, wprzytula commented
Addressed both comments:
- Box'ed predicate instead of a generic
- is_enabled() stub for is_alive()

2023-01-19 16:08 UTC, havaker requested changes
Please drop this commit https://github.com/havaker/scylla-rust-driver/pull/6/commits/a11451367153f9651b05b02fea7160f54cd09f73

2023-01-19 16:13 UTC, wprzytula commented
> Please drop this commit [a114513](https://github.com/havaker/scylla-rust-driver/commit/a11451367153f9651b05b02fea7160f54cd09f73)

Ok, but now `latency_aware.rs` is not deleted; I've made a mistake during recent rebase on main, so we probably need to remove it again. I would suggest removing it in a new commit, and I'll handle it in a final cleanup of this PR.

2023-01-19 16:25 UTC, havaker commented
Please rebase to `havaker:lb2`.

2023-01-20 08:46 UTC, wprzytula commented
> Please rebase to `havaker:lb2`.

done.

2023-01-22 16:29 UTC, closed without merging